services:
  api:
    build: .
    container_name: t2_api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/t2_api?schema=public
      MONGO_URI: mongodb://mongo:27017/t2_api
      JWT_SECRET: troque_esta_chave_em_producao
      JWT_EXPIRES_IN: 1h
      BCRYPT_SALT_ROUNDS: 10
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:16-alpine
    container_name: t2_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: t2_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: t2_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:

